service: practica4

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  region: us-east-1

functions:
  upload:
    handler: handler.uploadFile
    timeout: 60 # seconds
    memorySize: 512 # mb
    events:
      - http:
          path: /
          method: post

    environment:
       ACCESS_KEY_ID: AKIA2K6ZFIDZMOSD6FON
       SECRET_ACCESS_KEY: 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
       BUCKET: practica4